name: scan with KICS and upload SARIF

on:
 push:
   branches:
     - main

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-github-action
    steps:
      - uses: actions/checkout@v2
      - name: run kics Scan
        uses: Checkmarx/kics-github-action@v2.1.3
        with:
          path: 'iac-scan'
          ignore_on_exit: results
          output_path: 'results.sarif'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
